package view;

import javax.swing.*;

import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;



import model.LoginModel;
import controller.LoginController;

public class LoginView extends JFrame {
    private JTextField loginUsername;
    private JTextField loginPassword;
    private JTextField registerUsername;
    private JTextField registerPassword;
    private LoginController controller;

    public LoginView() {
        this.controller = new LoginController(new LoginModel(this));
        controller.setMyView(this);
        this.setTitle("Login / Register");
        this.setSize(800,600);
        this.setLocationRelativeTo(null); // centers the window - generated by AI
        this.setUp();
        this.setVisible(true);
    }
    
    private void setUp() {
        JPanel mainPanel = new JPanel(new BorderLayout()); // layout generated by AI
        mainPanel.setBackground(Color.darkGray);
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20)); // border generated by AI
        this.add(mainPanel);

        // center content panel (layout generated by AI)
        JPanel centerPanel = new JPanel();
        centerPanel.setBackground(new java.awt.Color(20, 25, 35));
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS)); // layout generated by AI

        //JLabel titleLabel = new JLabel("Login or Register");
        JLabel2D titleLabel = new JLabel2D("Login or Register");
        titleLabel.setForeground(new java.awt.Color(219, 237, 247));
        titleLabel.setOutlineColor(new java.awt.Color(119, 137, 147));
        titleLabel.setStroke(new BasicStroke(2f));
        titleLabel.setFont(new Font("Stencil", Font.PLAIN, 40));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment generated by AI
        centerPanel.add(Box.createRigidArea(new Dimension(0, 20))); // AI generated
        centerPanel.add(titleLabel);
        
        
        //Username Labels
        
        JLabel usernameLabel = new JLabel("Username");
        usernameLabel.setForeground(new java.awt.Color(219, 237, 247));
        usernameLabel.setFont(new Font("Stencil", Font.PLAIN, 15));
        usernameLabel.setAlignmentX(Component.RIGHT_ALIGNMENT); // alignment generated by AI
        usernameLabel.setMaximumSize(new Dimension(100,20));
        
        JLabel usernameLabel2 = new JLabel("Username");
        usernameLabel2.setForeground(new java.awt.Color(219, 237, 247));
        usernameLabel2.setFont(new Font("Stencil", Font.PLAIN, 15));
        usernameLabel2.setAlignmentX(Component.RIGHT_ALIGNMENT); // alignment generated by AI
        usernameLabel2.setMaximumSize(new Dimension(100,20));
        
        
        //Password Labels
        JLabel passwordLabel = new JLabel("Password");
        passwordLabel.setForeground(new java.awt.Color(219, 237, 247));
        passwordLabel.setFont(new Font("Stencil", Font.PLAIN, 15));
        passwordLabel.setAlignmentX(Component.RIGHT_ALIGNMENT); // alignment generated by AI
        passwordLabel.setMaximumSize(new Dimension(100,20));
        
        JLabel passwordLabel2 = new JLabel("Password");
        passwordLabel2.setForeground(new java.awt.Color(219, 237, 247));
        passwordLabel2.setFont(new Font("Stencil", Font.PLAIN, 15));
        passwordLabel2.setAlignmentX(Component.RIGHT_ALIGNMENT); // alignment generated by AI
        passwordLabel2.setMaximumSize(new Dimension(100,20));
        
        
        

        // bottom panel (layout generated by AI)
        JPanel bottomPanel = new JPanel();
        bottomPanel.setBackground(Color.darkGray);
        bottomPanel.setLayout(new BoxLayout(bottomPanel, BoxLayout.Y_AXIS)); // layout generated by AI

        loginUsername = new JTextField(20);
        loginUsername.setMaximumSize(new Dimension(200, 30));
        loginUsername.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        loginPassword = new JTextField(20);
        loginPassword.setMaximumSize(new Dimension(200, 30));
        loginPassword.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        JButton login = new JButton("Login");
        login.setFont(new Font("Stencil", Font.PLAIN, 15));
        login.setActionCommand("login");
        login.addActionListener(controller);
        login.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated
        

        registerUsername = new JTextField(20);
        registerUsername.setMaximumSize(new Dimension(200, 30));
        registerUsername.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        registerPassword = new JTextField(20);
        registerPassword.setMaximumSize(new Dimension(200, 30));
        registerPassword.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        JButton register = new JButton("Register");
        register.setFont(new Font("Stencil", Font.PLAIN, 15));
        register.setActionCommand("register");
        register.addActionListener(controller);
        register.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        TextLabel responseMessageLabel = new TextLabel();
        responseMessageLabel.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated
        responseMessageLabel.setForeground(Color.lightGray);
        controller.addObserver(responseMessageLabel);

        centerPanel.add(Box.createRigidArea(new Dimension(0, 20))); // AI generated
        centerPanel.add(usernameLabel);
        centerPanel.add(loginUsername);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        centerPanel.add(passwordLabel);
        centerPanel.add(loginPassword);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        bottomPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        centerPanel.add(login);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 50))); // AI generated
        centerPanel.add(usernameLabel2);
        centerPanel.add(registerUsername);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        centerPanel.add(passwordLabel2);
        centerPanel.add(registerPassword);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        bottomPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        centerPanel.add(register);
        centerPanel.add(responseMessageLabel);

        // add panels to main panel
        mainPanel.add(centerPanel, BorderLayout.CENTER); // AI generated layout
        mainPanel.add(bottomPanel, BorderLayout.SOUTH); // AI generated layout


        //adding a window listener for closing the app
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent) {
                System.exit(0);
            }
        });

        this.setVisible(true);
    }

    public String getLoginUsername() {
        return this.loginUsername.getText();
    }
    public String getLoginPassword() {
        return this.loginPassword.getText();
    }

    public String getRegisterUsername() {
        return this.registerUsername.getText();
    }
    public String getRegisterPassword() {
        return this.registerPassword.getText();
    }


    public static void main(String[] args) {
        new LoginView();
    }
}

