package view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import model.VictoryModel;
import controller.VictoryController;

public class VictoryView extends JFrame {
    private String username;
    private VictoryController controller;

    public VictoryView(String username) {
        this.username = username;
        this.controller = new VictoryController(new VictoryModel(this, username));
        controller.setMyView(this);
        this.setTitle("Victory");
        this.setSize(800,600);
        this.setLocationRelativeTo(null); // centers the window - generated by AI
        this.setUp();
        this.setVisible(true);
    }


    private void setUp() {
        JPanel mainPanel = new JPanel(new BorderLayout()); // layout generated by AI
        mainPanel.setBackground(Color.darkGray);
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20)); // border generated by AI
        this.add(mainPanel);

        // center content panel (layout generated by AI)
        JPanel centerPanel = new JPanel();
        centerPanel.setBackground(Color.darkGray);
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS)); // layout generated by AI

        JLabel titleLabel = new JLabel("Victory");
        titleLabel.setForeground(Color.LIGHT_GRAY);
        titleLabel.setFont(new Font("Comic Sans MS", Font.BOLD, 24));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment generated by AI
        centerPanel.add(titleLabel);

        JLabel userLabel = new JLabel("Congrats " + username);
        userLabel.setForeground(Color.LIGHT_GRAY);
        userLabel.setFont(new Font("Comic Sans MS", Font.BOLD, 24));
        userLabel.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment generated by AI
        centerPanel.add(userLabel);


        // bottom panel (layout generated by AI)
        JPanel bottomPanel = new JPanel();
        bottomPanel.setBackground(Color.darkGray);
        bottomPanel.setLayout(new BoxLayout(bottomPanel, BoxLayout.Y_AXIS)); // layout generated by AI

        JButton play = new JButton("Play Again");
        play.setActionCommand("play");
        play.addActionListener(controller);
        play.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        JButton leaderboard = new JButton("Leaderboard");
        leaderboard.setActionCommand("leaderboard");
        leaderboard.addActionListener(controller);
        leaderboard.setAlignmentX(Component.CENTER_ALIGNMENT); // alignment is AI generated

        JButton exit = new JButton("Exit");
        exit.setActionCommand("exit");
        exit.addActionListener(controller);
        exit.setAlignmentX(Component.CENTER_ALIGNMENT);

        centerPanel.add(play);
        centerPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        bottomPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        bottomPanel.add(Box.createRigidArea(new Dimension(0, 10))); // AI generated
        centerPanel.add(leaderboard);
        centerPanel.add(exit);

        // add panels to main panel
        mainPanel.add(centerPanel, BorderLayout.CENTER); // AI generated layout
        mainPanel.add(bottomPanel, BorderLayout.SOUTH); // AI generated layout


        //adding a window listener for closing the app
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent) {
                System.exit(0);
            }
        });

        this.setVisible(true);
    }

}